spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/lab3?autoReconnect=true&useSSL=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 8086


